### ISSUE TITLE
ICA 03 - General

### ISSUE THREAD

**Issue by Zwirc** [IS-105-GitGroup/IS-105-Gruppe1#36]
- [x] timestamp i test -gjort iso_test ; mangler ascii_test

- [x] Bruk log pakken?

- [x] Forklare forskjell på utskrift %q og %c (String , char)

- [x] passe på modulisering slik at du kan kjøre oppgaven avskilt.
Bedre struktur av gode, unngå unødvendig kode.
Hva gang commitet til github, kjør alle tester.

**Comment by Eirikas** [comment]
passe på modulisering slik at du kan kjøre oppgaven avskilt. 
Bedre struktur av gode, unngå unødvendig kode.
Hva gang commitet til github, kjør alle tester.

**Comment by HelleTrygsland** [comment]
Forskjellene på %q og %c:
%c skriver ut en karakter av gangen og prøver å tolke det så godt som
mulig innenfor utvidet ASCII kodesett
fmt.Printf("%c\n", "\xbd\xb2\x3d\xbc\x20\xe2\x8c\x98")
Resultatet er: "[½ ² = ¼ â ]"

%q representerer en tekstreng angitt med dobble anførselstegn og
“flykter” (bruker ordet “escape” på engelsk når man skal fortelle parseren at
et tegn skal ikke tolkes på en pre-definert måte og erstatte disse med Go’s
syntaks for byte) alle tegn som ikke er skrivbare; for eksempel, samsvarer
ikke bytesekvensen (BD, B2 og BC er problemet) med UTF-8 kode, som Go
konsekvent bruker
fmt.Printf("%q\n", "\xbd\xb2\x3d\xbc\x20\xe2\x8c\x98")
Resultatet er: "\xbd\xb2=\xbc ⌘"

Hvor skal vi skrive dette inn i oppgaven? Foreløpig står det ICA04 på readme for ICA03

**Comment by Zwirc** [comment]
Standalone filer fikset, fikset log

**Comment by iMatMan** [comment]
lagt til timestamp på iso_test.go

**Comment by Zwirc** [comment]
Mathias: denne er synlig ved go test -v fil.go , se vedlegg :)
